AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: >
  Receive an Amazon S3 event input[image], processes the image. i.e resizes the image in the source bucket and saves the output to the target bucket.

Parameters:
  debugMODE:
    Description: Do you want to enable logging.
    Default: "False"
    Type: String
    AllowedValues: ["True", "False"]
    ConstraintDescription: Must be boolean.
  FunctionNameSuffix:
    Description: 'Suffix to append to the Lambda functions.'
    Type: 'String'
    Default: '-Mystique'

Globals:
  Function:
    Runtime: python3.7
    Timeout: 10
    MemorySize: 128
    Environment:
      Variables:
        DEBUG_MODE:
          Ref: debugMODE

Resources:

  EventProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Description: 'AWS Lambda to process newly uploaded images and store in target bucket'
      FunctionName: !Sub 'EventProcessor${FunctionNameSuffix}'
      Handler: serverless-s3-event-processor.lambda_handler
      CodeUri: ./src/*
      Events:
        EventTrigger1:
          Type: S3
          Properties:
            Bucket: !Ref SrcEventBucket
            Events: s3:ObjectCreated:*
      Policies: 
        - AWSLambdaExecute # Managed Policy
        # - Version: '2012-10-17' # Policy Document
        #   Statement:
        #     - Effect: Allow
        #       Action:
        #         - s3:GetObject
        #         - s3:GetObjectACL
        #        Resource: !GetAtt SrcEventBucket.Arn

  SrcEventBucket:
    Type: AWS::S3::Bucket
  TgtEventBucket:
    Type: AWS::S3::Bucket

Outputs:
  SrcS3Bucket:
    Description: Source S3 Bucket that triggers the Lambda
    Value: !Ref SrcEventBucket
  TgtS3Bucket:
    Description: Target S3 Bucket that triggers the Lambda
    Value: !Ref TgtEventBucket
  EventProcessorFunction:
    Description: ARN for the EventProcessor Lambda Function
    Value: !GetAtt EventProcessor.Arn